paybill/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('pb.urls')), # Main Application
]

pb/urls.py
from django.conf.urls import patterns, url
from pb import views
# from pb.views import some class base views
from django.conf import settings


urlpatterns = patterns('',
        # Public info pages for everyone
        url(r'^$', views.index, name='index'),

        # Merchent Section
        url(r'^register/$', views.register, name='register'),
        url(r'^login/$', views.login_user, name='login_user'),
        # Merchent Bill Processing Requests
        url(r'claim/(?P<request_id>[0-9]+)/$', views.claim_request, name='claim_request'),
        url(r'confirm-request/(?P<request_id>[0-9]+)/$', views.confirm_request, name='confirm_request'),
        url(r'mercehenttimeleft/(?P<request_id>[0-9]+)/$', views.merchent_time_left, name='merchent_time_left'),
        url(r'latest-requests/$', views.bill_requests, name='bill_requests'),
        url(r'completed-requests/$', views.merchent_completed_requests, name='merchent_completed_requests'),
        url(r'claimed-requests/$', views.merchent_claimed_requests, name='merchent_claimed_requests'),
        url(r'dashboard/$', views.merchent_dashboard, name='merchent_dashboard'),
        # Merchent Payments
        url(r'payments/$', views.all_payments, name='all_payments'),
        url(r'createpayment/$', views.create_payment, name='create_payment'),
        # Merchent Settings
        url(r'settings/password/$', views.change_password, name='change_password'),

        # Ajax for front-end user who submits bill request!
        url(r'^track/$', views.track_bill_request, name='track_bill_request'),
        url(r'^submitrequestdata/$', views.submit_request_data, name='submit_request_data'),
        url(r'getcompanies/(?P<bill_type>[-\w]+)/$', views.get_companies, name='get_companies'),
        url(r'timeleft/(?P<request_id>[0-9]+)/$', views.time_left_to_pay, name='time_left_to_pay'),
        url(r'isrequestpaid/(?P<request_id>[0-9]+)/$', views.is_request_paid, name='is_request_paid'),

        # Logout for merchents
        url(r'^logout/$', views.user_logout, name='logout'),)
if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'^media/(?P<path>.*)',
        'serve',
        {'document_root': settings.MEDIA_ROOT}),)

#-------------------------------------
# ----------- Merchent Area-----------
#-------------------------------------
# Paymets -----------
#--------------------
# Approved Payments
# Pending Payments
# Paid Payments
# OnHold Payments
#-----------------------------
# Dashboard and Requests -----
#-----------------------------
# Pending Requests
# To be Processed Requests
#-----------------------------
# Sign up and Login -----
#-----------------------------
# Pending Requests
# To be Processed Requests
#-------------------------------------
# ----------- Frontend Users ---------
#-------------------------------------
# Submit Request -----------
#---------------------------
# Main details
# 

pb/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
#######################
# Models for the PB app
#######################


# Inherting Users to make them Merchents
class Merchent(models.Model):
	# --- One to One Relationship key to connect to django default User Model
	user = models.ForeignKey(User)
	# --- Contact Number
	contact_num = models.CharField(max_length=128)
	# --- Landline (Default Null)
	landline_num = models.CharField(max_length=128)
	# --- CNIC (File Photo Field)
	cnic_photo = models.ImageField(upload_to='cnic_images', blank=True)
	# --- Selfi Holding CNIC (Default Null)
	cinc_selfi_photo = models.ImageField(upload_to='cnic_selfi_images', blank=True)
	# --- Email Verified Status
	isverified_email = models.BooleanField(default=False)
	# --- Account Status (string)
	is_account_active = models.BooleanField(default=False)
	# --- Is Approved by Admin (Default to False)
	is_admin_approve = models.BooleanField(default=False)
	# --- IS Blocked by admin (default to false)
	is_admin_blocked = 	models.BooleanField(default=False)
	# --- ID number provided by billing company
	billing_id_number = models.CharField(max_length=128)
	# --- Balance Earned in total ever on our site
	total_earnings = models.IntegerField(default=0)
	# --- Balance available to widthdraw
	balance_available = models.IntegerField(default=0)

	def __str__(self):
		# get user by merchent
		return self.user.username


# Requests Model to Store Requests Mostly refered as bill request
class Request(models.Model):
	# --- Current time when request was submitted (Timestamp)
	date_time = models.DateTimeField(auto_now=True)
	# --- Type (Forign key to Request type Model)
	bill_type = models.CharField(max_length=128)
	# --- Bill Payment Companies (Create a New Model Forign KEy)
	billing_company = models.CharField(max_length=128)
	# --- Payment form (Default to BTC for now)
	payment_method = models.CharField(max_length=128, default="BTC")
	# --- Country Name (String Perhaps create additional Table)
	country = models.CharField(max_length=128, default="Pakistan")
	# --- Due Bill amount in PKR (Float)
	pkr_bill_amount = models.IntegerField(default=0)
	# --- Contact Number (String or Numric we'll see that)
	contact_num = models.CharField(max_length=128)
	# --- Bill Indentifier Number (String)
	bill_id_num = models.CharField(max_length=128)
	# --- Payment status isPaid or completed? (Boolean)
	is_paid = models.BooleanField(default=False)
	# --- Is Request Processed Status? or Pending (Boolean)
	is_completed = models.BooleanField(default=False)
	# --- Error / Issue Message
	issue_message = models.TextField(default="No Error or Issue all Clear ")
	# --- In response to completion request TXID
	confirmation_txid = models.CharField(default="No Information ID Provided",  max_length=128)
	# --- BTC confirmations count [int]
	btc_confirmations = models.IntegerField(default=0)
	# --- BTC Wallet on which payment was received
	btc_address = models.CharField(max_length=400)
	# --- Amount of BTC recived
	btc_amount = models.FloatField(default=0)
	# --- Email assoicated with the request to send out Automated email
	email_address = models.CharField(max_length=100, blank=True)
	# --- if we have more then 6 confirmations then we mark this transaction completed
	payment_completed = models.BooleanField(default=False)
	# --- can be completed token expires after 30 mints
	request_token = models.BooleanField(default=True)
	# --- Time at Request was Claimed
	time_claimed_on = models.DateTimeField(blank=True)
	# --- who claims the Bill Request --- #
	claimer = models.ForeignKey(Merchent,default="1")

	def __str__(self):
		return str(self.pk)





# Payments to User Model to store payments for users 
# One to many relationship to User Merchent Model
class Payment(models.Model):
	# --- Timestamp when payment is created
	date_time = models.DateTimeField(auto_now=True)
	# --- The merchent to whom the payment belongs (ONE TO many to Merchents)
	merchent = models.ForeignKey(Merchent)
	# --- Payment Status (Error, Pending, onHold, Paid )
	ispaid = models.BooleanField(default=False)
	# --- Payment amount
	payment_amount = models.IntegerField(default=0)
	# --- Paid via (BTC or Cash)
	payment_method = models.CharField(max_length=128)
	# --- Error Message
	error_message = models.TextField(default="None")


class Company(models.Model):
	# --- Name of the company
	name = models.CharField(max_length=128)
	# --- Supported Bill type
	bill_type = models.CharField(max_length=128)
	# --- Country in Operating
	country = models.CharField(max_length=128)

	def __str__(self):
		return self.name

pb/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User
from django.core import serializers
from django.db.models import Q

# App Specific Imports Self Made 
from pb.forms import UserForm, MerchentForm
from pb.models import Merchent, Request, Payment, Company

#Standard Import related to Python
from datetime import datetime, timezone
import json, time, requests


def index(request):
    # Just return the Landing page template back to the user!
    return render(request, "index.html")


# --- MERCHENT LOGIN --- #

def login_user(request):
    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
        # Gather the username and password provided by the user.
        # This information is obtained from the login form.
                # We use request.POST.get('<variable>') as opposed to request.POST['<variable>'],
                # because the request.POST.get('<variable>') returns None, if the value does not exist,
                # while the request.POST['<variable>'] will raise key error exception
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Use Django's machinery to attempt to see if the username/password
        # combination is valid - a User object is returned if it is.
        user = authenticate(username=username, password=password)

        # If we have a User object, the details are correct.
        # If None (Python's way of representing the absence of a value), no user
        # with matching credentials was found.
        if user:

            # Is the account active? It could have been disabled.
            if user.is_active:
                # If the account is valid and active, we can log the user in.
                # We'll send the user back to the homepage.
                login(request, user)
                return HttpResponseRedirect('/')
            else:
                # An inactive account was used - no logging in!
                return HttpResponse("Your Rango account is disabled.")
        else:
            # Bad login details were provided. So we can't log the user in.
            print ("Invalid login details: {0}, {1}".format(username, password))
            return HttpResponse("Invalid login details supplied. Go back and try again")
    # The request is not a HTTP POST, so display the login form.
    # This scenario would most likely be a HTTP GET.
    else:
        # No context variables to pass to the template system, hence the
        # blank dictionary object...
        return render(request, 'pb/login.html', {})

# --- MERCHENT REGISTERATION ---#
def register(request):

    # A boolean value for telling the template whether the registration was successful.
    # Set to False initially. Code changes value to True when registration succeeds.
    registered = False

    # If it's a HTTP POST, we're interested in processing form data.
    if request.method == 'POST':
        # Attempt to grab information from the raw form information.
        # Note that we make use of  UserForm 
        user_form = UserForm(data=request.POST)
        merchent_form = MerchentForm(data=request.POST)

        # If the two forms are valid...
        if user_form.is_valid() and merchent_form.is_valid():
            # Save the user's form data to the database.
            user = user_form.save()

            # Now we hash the password with the set_password method.
            # Once hashed, we can update the user object.
            user.set_password(user.password)
            user.save()

            merchent = merchent_form.save(commit=False)
            merchent.user = user

            # Did the user provide a merchent picture?
            # If so, we need to get it from the input form and put it in the merchent model.
            if 'cinc_selfi_photo' in request.FILES:
                merchent.cinc_selfi_photo = request.FILES['cinc_selfi_photo']
            if 'cnic_photo' in request.FILES:
                merchent.cnic_photo = request.FILES['cnic_photo']
            # Now we save the UserProfile model instance.
            merchent.save()

            # Update our variable to tell the template registration was successful.
            registered = True

        # Invalid form or forms - mistakes or something else?
        # Print problems to the terminal.
        # They'll also be shown to the user.
        else:
            print (user_form.errors and merchent_form.errors)

    # Not a HTTP POST, so we render our form using two ModelForm instances.
    # These forms will be blank, ready for user input.
    else:
        user_form = UserForm()
        merchent_form = MerchentForm()

    # Render the template depending on the context.
    return render(request,
            'pb/register.html',
            {'user_form': user_form, 'registered': registered, 'merchent_form': merchent_form} )

# Getting the User Logged out of the System
@login_required
def user_logout(request):
    # Since we know the user is logged in, we can now just log them out.
    logout(request)
    
    # Take the user back to the homepage.
    return HttpResponseRedirect('/')


@login_required
def user_logout(request):
    # Since we know the user is logged in, we can now just log them out.
    print("user was logged in and we logged him out")
    logout(request)
    
    # Take the user back to the homepage.
    return HttpResponseRedirect('/')

# --- Requests --- #

#####################################################
####                                             ####
####  Merchent Area Requests view and Processing ####
####                                             ####
#####################################################

# --- Requests --- #

# .. # .. /claim-request/<request_id>
# .. Claim a request to process by passing the req id
def claim_request(request, request_id):
    # get the object
    bill_request = Request.objects.get(pk=request_id)
    # .. Make sure if the request_token is set to false 
    if bill_request.request_token == True:
    # .. add or update the request claimed time field in database
        bill_request.time_claimed_on = datetime.now(timezone.utc)
        logged_in_merchent = Merchent.objects.get(user_id=request.user.pk)
        bill_request.claimer = logged_in_merchent
        bill_request.request_token = False
        bill_request.save()
        # .. redirect to confim request completed page /request_confirm/<request_id>
        redirect_url = "/confirm-request/" + str(bill_request.pk)
        return HttpResponseRedirect(redirect_url)
    else:
        return HttpResponse("not available for claim")


# .. /confirm-request/<request_id>
# .. Mark the request completed by providing the confirmation number
def confirm_request(request, request_id):
    # check if we got the form submitted or get request
    if request.method == 'POST':
        txid = request.POST.get('txid')
        # Validate this string before putting it in the database
        ## todo
        # get the object by id
        bill_request = Request.objects.get(pk=request_id)
        # save it in database
        bill_request.confirmation_txid = txid
        bill_request.is_completed = True
        # save it in DB
        bill_request.save()
        # render the form
        # send email todo
        context = {
            
            "request" : bill_request,
            "messagetype" : "success"
        }
        return render(request, 'pb/confirm_request.html', context )
    else:
        # display the request information

        bill_request = Request.objects.get(pk=request_id)

        print("Request Status is : ", bill_request.is_completed  )

        # get the request information
        context = {

            "request" : bill_request
        
        }
        return render(request, 'pb/confirm_request.html', context )



# Pool of Bill Request shown all Merchents so they can process requests
def bill_requests(request):
    # get all the objects with respect to unclaimed and have token to setten to false
    bill_requests_list = Request.objects.all().filter(request_token=True, is_completed=False)

    paginator = Paginator(bill_requests_list, 10) # Show 10 bills per page

    page = request.GET.get('page')
    try:
        bill_requests = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        bill_requests = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        bill_requests = paginator.page(paginator.num_pages)

    context = {

        "bill_requests" : bill_requests 

    }

    return render(request, "pb/latest_requests.html", context)


# Claimed Un Processed Requests
def merchent_claimed_requests(request):
    logged_in_merchent = Merchent.objects.get(user_id=request.user.pk)
    bill_requests = Request.objects.all().filter(claimer_id=logged_in_merchent.pk, is_completed=False)

    context = {

        "bill_requests" : bill_requests

    }

    return render(request, "pb/claimed_requests.html", context)
    


# Completed Requests by Logged in Merchent User
def merchent_completed_requests(request):
    bill_requests = Request.objects.all().filter(claimer_id=request.user.pk, is_completed=True)

    context = {

        "bill_requests" : bill_requests

    }
    
    return render(request, "pb/completed_requests.html", context)



# --- DASHBOARD --- #
def merchent_dashboard(request):

pb/templates/pb/all_payments.html
{% extends 'layout.html' %}
{% load humanize %}

{% block title %} Confirm Bill Request {{ request.pk }}{% endblock %}

{% block content %}


<!-- Hero Content -->
<div class="bg-primary-dark-op">
    <section class="content content-full content-boxed overflow-hidden">
    <!-- Section Content -->
        <div class=" text-center">
            <h1 class="h2 text-white push-10">Payment History</h1>
            <h2 class="h5 text-white-op">Most Recent Payment History can be Accessed Below</h2>
        </div>
    <!-- END Section Content -->
    </section>
</div>
<!-- END Hero Content -->


<!-- Content -->
<div class="bg-white">
    <section class="content content-boxed">
    <!-- Section Content -->
        <div class="row items-push push-50-t push-30">

            <div class="col-lg-8">

                <!-- Bordered Table -->

                <div class="block">
                        <div class="block-content">
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th class="text-center">ID</th>
                                        <th>Date & Time</th>
                                        <th class="hidden-xs">Method</th>
                                        <th class="hidden-xs">Message</th>
                                        <th class="hidden-xs">Amount <sup>PKR</sup></th>
                                        <th class="text-center">Status</th>
                                    </tr>
                                </thead>
                                <tbody>

                                    {% for payment in payments %}
                                    <tr>

                                        <td class="text-center">{{ payment.pk }}</td>

                                        <td>{{ payment.date_time }}</td>
                                        
                                        <td>{{ payment.payment_method }}</td>

                                        <td>{{ payment.error_message }}</td>
                                        
                                        <td class="hidden-xs">
                                            <span class="label label-info">{{ payment.payment_amount|intcomma}}</span>
                                        </td>

                                        <td class="text-center">
                                            <div class="btn-group">
                                                {% if payment.ispaid == True %}
                                                <span class="label label-success">Paid</span>
                                                {% else %}
                                                <span class="label label-warning">Processing</span>
                                                {% endif %}
                                            </div>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>

                <!-- END Bordered Table -->
            </div>



            <div class="col-lg-4">
                <!-- Log In Form -->
            </br>
        
                <form class="form-horizontal" id="payment_form" method="post" action="/createpayment/">
                
                {% csrf_token %}

                    <div class="col-xs-6">
                        <div class="form-group">
                            <div class="col-xs-12">
                                <div class="form-material form-material-primary">
                                    <input class="form-control" type="text" id="requestamount" name="requestamount" placeholder="less then {{ merchent.balance_available }}">
                                    <label for="requestamount">Request Amount</label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-6">
                        <div class="form-group">
                            <div class="col-xs-12">
                                <div class="form-material form-material-primary">
                                    <input class="form-control" type="text" id="paymentmethod" name="paymentmethod" placeholder="BTC, Cash etc">
                                    <label for="paymentmethod">Payment Method</label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12">
                        <div class="form-group">
                            <div class="col-xs-12 col-sm-12 ">
                                <button class="btn btn-block btn-primary" type="submit"><i class="fa fa-arrow-right pull-right"></i> Request Payment</button>
                            </div>
                        </div>
                    </div>


                </form>
                <!-- END Log In Form -->

                    
            </div>
        
        </div>
    <!-- END Section Content -->
    </section>
</div>
<!-- END Content -->
{% endblock %}

pb/templates/pb/register.html
{% extends 'layout.html' %}

{% block title %} Merchent  Login {% endblock %}

{% block content %}



<!-- Hero Content -->
<div class="bg-primary-dark-op">
    <section class="content content-full content-boxed overflow-hidden">
    <!-- Section Content -->
        <div class="text-center">
            <h1 class="h2 text-white push-10">Merchent Sign Up.</h1>
            <h2 class="h5 text-white-op">Process Bills, Get Paid, Grow like never before let's get you register first</h2>
        </div>
    <!-- END Section Content -->
    </section>
</div>
<!-- END Hero Content -->




        {% if registered %}
        Rango says: <strong>thank you for registering!</strong>
        <a href="/">Return to the homepage.</a><br />
        {% else %}




























<!-- Content -->
<div class="bg-white">

    <section class="content content-boxed">
    <!-- Section Content -->
        <div class="row items-push push-50-t push-30">

            <div class="col-md-6 col-md-offset-3">
                




                <form id="user_form" class="form-horizontal" action="/register/" method="post">


                    {% csrf_token %}


                    {% if user_form.errors %}
                        {% for field in user_form %}
                            {% for error in field.errors %}
                                <div class="alert alert-error">
                                    <strong>{{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                        {% endfor %}
                        {% for error in user_form.non_field_errors %}
                            <div class="alert alert-error">
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endif %}


                    <div class="form-group">
                        <div class="col-xs-12">
                            <div class="form-material form-material-success">
                                <input class="form-control" type="text" id="id_username" name="username" placeholder="Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.">
                                <label for="id_username">Username</label>
                            </div>
                        </div>
                    </div>




                    <div class="form-group">
                        <div class="col-xs-12">
                            <div class="form-material form-material-success">
                                <input class="form-control" type="email" id="id_email" name="email" placeholder="Please provide your email">
                                <label for="id_email">Email</label>
                            </div>
                        </div>
                    </div>
                    



                    <div class="form-group">
                        <div class="col-xs-12">
                            <div class="form-material form-material-success">
                                <input class="form-control" type="password" id="id_password" name="password" placeholder="Choose a strong password..">
                                <label for="id_password">Password</label>
                            </div>
                        </div>
                    </div>




                    <div class="form-group">
                        <div class="col-xs-12">
                            <div class="form-material form-material-success">
                                <input class="form-control" type="text" id="id_contact_num" name="contact_num" placeholder="Mobile or Office">
                                <label for="id_contact_num">Contact Number</label>
                            </div>
                        </div>
                    </div>




                    <div class="form-group">
                        <div class="col-xs-12">
                            <div class="form-material form-material-success">
                                <input class="form-control" type="text" id="id_billing_id_number" name="billing_id_number" placeholder="Idenfication Number provided to you from Billing Company">
                                <label for="id_billing_id_number">Billing ID Number</label>
                            </div>
                        </div>
                    </div>
                    
                    

                    

                    <div class="form-group">
                        <label class="col-xs-12" for="id_cnic_photo">CNIC Photo</label>
                        <div class="col-xs-12">
                            <input type="file" id="id_cnic_photo" name="cnic_photo">
                        </div>
                    </div>





                    <div class="form-group">
                        <div class="col-xs-12 text-center">
                            <label class="css-input switch switch-sm switch-success">
                                <span></span> By clicking "Sign Up" you agree with 
                                <a data-toggle="modal" data-target="#modal-signup-terms" href="#">terms &amp; conditions</a>
                            </label>
                        </div>
                    </div>




                    <div class="form-group">
                        <div class="col-sm-6 col-sm-offset-3">
                        <button class="btn btn-block btn-success" type="submit"><i class="fa fa-plus pull-right"></i> Sign Up</button>
                        </div>
                    </div>



                </form>
            </div>
        </div>
    <!-- END Section Content -->
    </section>
</div>
<!-- END Content -->














{% endif %}







<!-- Terms Modal -->
<div class="modal fade" id="modal-signup-terms" tabindex="-1" role="dialog" aria-hidden="true">
<div class="modal-dialog modal-dialog-popout">
<div class="modal-content">
<div class="block block-themed block-transparent remove-margin-b">
<div class="block-header bg-primary-dark">
<ul class="block-options">
<li>
<button data-dismiss="modal" type="button"><i class="si si-close"></i></button>
</li>
</ul>
<h3 class="block-title">Terms &amp; Conditions</h3>
</div>
<div class="block-content">
<p>Dolor posuere proin blandit accumsan senectus netus nullam curae, ornare laoreet adipiscing luctus mauris adipiscing pretium eget fermentum, tristique lobortis est ut metus lobortis tortor tincidunt himenaeos habitant quis dictumst proin odio sagittis purus mi, nec taciti vestibulum quis in sit varius lorem sit metus mi.</p>
<p>Dolor posuere proin blandit accumsan senectus netus nullam curae, ornare laoreet adipiscing luctus mauris adipiscing pretium eget fermentum, tristique lobortis est ut metus lobortis tortor tincidunt himenaeos habitant quis dictumst proin odio sagittis purus mi, nec taciti vestibulum quis in sit varius lorem sit metus mi.</p>
<p>Dolor posuere proin blandit accumsan senectus netus nullam curae, ornare laoreet adipiscing luctus mauris adipiscing pretium eget fermentum, tristique lobortis est ut metus lobortis tortor tincidunt himenaeos habitant quis dictumst proin odio sagittis purus mi, nec taciti vestibulum quis in sit varius lorem sit metus mi.</p>
<p>Dolor posuere proin blandit accumsan senectus netus nullam curae, ornare laoreet adipiscing luctus mauris adipiscing pretium eget fermentum, tristique lobortis est ut metus lobortis tortor tincidunt himenaeos habitant quis dictumst proin odio sagittis purus mi, nec taciti vestibulum quis in sit varius lorem sit metus mi.</p>
<p>Dolor posuere proin blandit accumsan senectus netus nullam curae, ornare laoreet adipiscing luctus mauris adipiscing pretium eget fermentum, tristique lobortis est ut metus lobortis tortor tincidunt himenaeos habitant quis dictumst proin odio sagittis purus mi, nec taciti vestibulum quis in sit varius lorem sit metus mi.</p>
</div>
</div>
<div class="modal-footer">
<button class="btn btn-sm btn-default" type="button" data-dismiss="modal">Close</button>
<button class="btn btn-sm btn-primary" type="button" data-dismiss="modal"><i class="fa fa-check"></i> I agree</button>
</div>
</div>
</div>
</div>
<!-- END Terms Modal -->


{% endblock %}